name: "secret-vault-github-action-plugin"
description: "Delinea DevOps Secrets Vault (DSV) GitHub Actions Plugin allows you to access and reference your Secrets data available for use in GitHub Actions"

inputs:
  domain:
    description: "DSV Tenant"
    required: true
  clientId:
    description: "DSV Tenant"
    required: true
  clientSecret:
    description: "DSV Tenant"
    required: true
  setEnv:
    description: "DSV Tenant"    
    required: true
  retrieve:
    description: "DSV Tenant"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    DOMAIN: ${{ inputs.domain }}
    CLIENT_ID: ${{ inputs.clientId }}
    CLIENT_SECRET: ${{ inputs.clientSecret }}
    SET_ENV: ${{ inputs.setEnv }}
    RETRIEVE: ${{ inputs.retrieve }}